[SystemSettings]
r.SecondaryScreenPercentage.GameViewport=50
r.Kuro.MaterialDesktopQualityShoulderRender=0
r.StaticMeshLODDistanceScale=0.8
r.ScreenSizeCullRatioFactor=10
r.Kuro.KuroEnableFFTBloom=0
r.Kuro.KuroEnableToonFFTBloom=0
r.Kuro.KuroBloomStreak=1
r.EnableLensflareSceneSample=1
r.SceneColorFringeQuality=0
r.AmbientOcclusionMaxQuality=0
r.Shadow.DistanceScale=0.5
r.Shadow.RadiusThreshold=0.05
r.Shadow.MaxResolution=256
r.Shadow.PerObjectShadowMapResolution=256
r.Shadow.PerObjectResolutionMax=256
r.Shadow.ForbidHISMShadowStartIndex=0
r.DetailMode=0
r.MaterialQualityLevel=2
r.KuroMaterialQualityLevel=2
foliage.CullAll=1
foliage.DensityScaleLOD.DrawCallOptimize=1
r.ViewDistanceScale=0.8
r.SSR.Quality=0
r.Streaming.QueriedAssetLoadFirst=1
r.Kuro.InteractionEffect.EnableFoliageEffect=0
r.Kuro.InteractionEffect.UseCppWaterEffect=0
r.Kuro.InteractionEffect.EnableBushInteractionEffect=0
r.KuroVolumeCloudEnable=0
r.SSFS=0
r.VRS.EnableMaterial=false
r.VRS.EnableMesh=false
wp.Runtime.PlannedLoadingRangeScale=0.5
;기타
r.EarlyZPass=1
r.EarlyZPassOnlyMaterialMasking=1
r.HZB.Culling=1
fx.NiagaraScript.StripByteCodeOnLoad=1
Niagara.GPUCulling=1
r.AOAsyncBuildQueue=1
r.EnableAsyncComputeTranslucencyLightingVolumeClear=1
r.ho.QueryWait=0
r.HeightFogOptimize=1
r.MaterialParameterLegacyChecks=0
r.OptimizeGameThreadWaiting=1

[/Script/Engine.RendererSettings]
r.RayTracing.LoadConfig=0